### ISSUE TITLE
Let's join forces!

### ISSUE THREAD

**Issue by MrNaif2018** [CypherpunkPay/CypherpunkPay#12]
Hello, creator of BitcartCC here.
Nice project! I recently saw it being added to the awesome payment processors list.
In the PR it was told that it is "the only realistic and maintained alternative to BTCPay Server". Wanted to tell you that there's another one (:
[BitcartCC](https://github.com/bitcartcc/bitcart) is also an alternative to btcpay, created back in 2019.
Our projects share similar values: light by default, but ability to use full nodes if needed, ability to install minimal things and it will work (we have a system of independent components instead of one big component like btcpay has)
I saw the system requirements of cypherpunkpay which said "1 gb RAM", and I knew one possible way of how could it work, as we also have same system requirements (:
I searched the repo for electrum, and indeed found it is being used.
Initially I thought electrum networking was used too and wanted to suggest that we have already did it before, but actually not.
So looks like cypherpunkpay by default parses different block explorers API, right?

What I want to suggest you is: what about joining forces? I invite you to join the BitcartCC project, which focuses on similar values like your project, is also written in python and focuses on being lightweight while still functional and secure.

I will help you out and answer all questions about the implementation, which part of the code does what, etc. If you are interested I can tell more about the project, we can contact via any way comfortable for you (email/keybase/telegram/discord, etc.)

I know, writing a project is hard and you probably wouldn't want to do it. But two people working on the same project are more likely to yield more features than 2 people working on different projects (: We are searching for developers and you would really be welcome in our community.

If you wonder how it works, in short: instead of importing only a subset of utilities from electrum for i.e. hashing purposes, I found a way to use electrum as a python library, and at our core I extended electrum's daemon functionality with some more features like dynamic wallet loading, websocket notifications of events and more. So electrum SPV networking model is used and it is all handled by electrum, which allows us to support bitcoin, lightning network as well as other coins based on electrum with minimal code modifications. But something like monero is possible too, just creating a custom daemon is needed. The daemon exposes a JSONRPC 2.0 interface to call various methods to send payments/query blockchain/watch blockchain, then there is a merchants API which handles the payment processing part, as well as two independent and not required UIs: admin panel and store. That's a short description of how it works.

I mean, a single-process daemon is great, but with time it won't be single-process probably. When you will need to scale to handle more requests for example, sqlite can no longer be used as it is not designed for concurrent writes, so postgres would still be needed. Maybe you would need some kind of inter-process communication or cache source-redis would be needed. Or when you scale to more than 1 wallet at a time, to handle more requests possibly you would need to start a few web workers handling requests, but you can't reliably run background tasks there, so an additional background worker process is introduced. I've come through all of this, starting from a single-file single-process app and to the independent components system we have now. Your project most likely will experience that as well. So why re-inventing the wheel and coming through a few refactor stages if you could join us where we solved some of those problems already? You're privacy-oriented look would help us too (:

In either case, thank you very much for your attention!

**Comment by CypherpunkDev** [comment]
Thanks for reaching out! I am excited to see BitcartCC being actively developed.

I'm grateful you shared some technical insights on how BitcartCC works under the hood and how it evolved.

CypherpunkPay will not compete in scenarios requiring super scalability - fortunately we already have BTCPay Server and BitcartCC for those! :-)

CypherpunkPay sits firmly on the **simplicity-at-all-costs** side of things. I believe there is tremendous value in standard apt-get installation/updates and single-process maintenance simplicity.

CypherpunkPay came into being **specifically** because both BitcartCC and BTCPay Server _de facto_ require Docker for production deployment. In delicate scenarios cryptocurrencies are supposed to be useful (whether anti-totalitarian activist or a free market business) you can't simply afford this amount of complexity and this many moving parts. Docker alone is a security nightmare.

You are correct about single-process technical challenges and limitations. Nevertheless CypherpunkPay will remain single-process as a **primary and default** mode of operation.

Where things get really hairy is the Lightning Network :-) I do not have a good answer here. The initial answer will be to not attempt to hide or abstract away LN complexity. The initial LN support will be targeted at LN technical power users.

I wish BitcartCC all the best in 2022!

**Comment by MrNaif2018** [comment]
I see, thank you very much for your reply!
So basically cypherpunkpay is like electrum personal server instead of electrumx/fulcrum full-blown servers handling many users
Makes sense if you just want to accept cryptocurrencies yourself and indeed removes many different complications!

Though just to add one note: we don't require docker, it's just a convenient way of installing and managing updates

Quite a few people e.g. installed bitcartcc daemon via python directly and used it in their custom workflows.

Good luck with LN support and all the best to you in 2022 too!
